// Skill name constants for type-safe usage
export const SKILLS = {
  C: "C",
  CPP: "C++",
  Java: "Java",
  Python: "Python",
  HTML: "HTML",
  CSS: "CSS",
  Tailwind: "Tailwind",
  TailwindCSS: "Tailwind CSS",
  Javascript: "Javascript",
  JavaScript: "JavaScript",
  Typescript: "Typescript",
  TypeScript: "TypeScript",
  React: "React",
  NodeJS: "Node.js",
  Node: "Node",
  Express: "Express",
  Hono: "Hono",
  MongoDB: "MongoDB",
  Postgres: "Postgres",
  PostgreSQL: "PostgreSQL",
  MySQL: "MySQL",
  NextJS: "Next.js",
  Expo: "Expo",
  Docker: "Docker",
  Vercel: "Vercel",
  Prisma: "Prisma",
  Neon: "Neon",
  Motion: "Motion",
  FramerMotion: "Framer Motion",
  Redux: "Redux",
  Zustand: "Zustand",
  Azure: "Azure",
  DigitalOcean: "DigitalOcean",
  Cursor: "Cursor",
  GraphQL: "GraphQL",
  tRPC: "tRPC",
  GSAP: "GSAP",
  Figma: "Figma",
  Postman: "Postman",
  VSCode: "VSCode",
  Gemini: "Gemini",
  GitHub: "GitHub",
  E2B: "E2B",
} as const;

export type SkillName = (typeof SKILLS)[keyof typeof SKILLS];
